**GRASP MATRIX FOR 1 FINGER 3D**


In [68]:
import numpy as np


In [69]:
def force_vec(s,t,n):
  z = np.column_stack([s,t,n])
  return z

s = np.array([1, 0, 0])
t = np.array([0, 0, -1])
n = np.array([0, 1, 0])
z=  force_vec(s,t,n)
print(z)

[[ 1  0  0]
 [ 0  0  1]
 [ 0 -1  0]]


In [70]:
#define function to calculate cross product
def cross_prod(x,s):
    A = [x[1]*s[2] - x[2]*x[1],
            x[2]*s[0] - x[0]*s[2],
            x[0]*s[1] - x[1]*s[0]]
    p = np.transpose(A)
    return p
def cross_prod(x,t):
    A = [x[1]*t[2] - x[2]*t[1],
            x[2]*t[0] - x[0]*t[2],
            x[0]*t[1] - x[1]*t[0]]
    q = np.transpose(A)
    return q
def cross_prod(x,n):
    A = [x[1]*n[2] - x[2]*n[1],
            x[2]*n[0] - x[0]*n[2],
            x[0]*n[1] - x[1]*n[0]]
    r = np.transpose(A)
    return r

# test
s = np.array([1, 0, 0])
t = np.array([0, 0, -1])
n = np.array([0, 1, 0])
x = np.array([-2, 0, 0])
p = cross_prod(x,t)
q = cross_prod(x,t)
r = cross_prod(x,n)
k= np.column_stack([p,q,r])
print(k)

[[ 0  0  0]
 [-2 -2  0]
 [ 0  0 -2]]


In [71]:
G = np.concatenate([z,k])
print(G)

[[ 1  0  0]
 [ 0  0  1]
 [ 0 -1  0]
 [ 0  0  0]
 [-2 -2  0]
 [ 0  0 -2]]


In [73]:
H= np.block([G,G])
print(H)

[[ 1  0  0  1  0  0]
 [ 0  0  1  0  0  1]
 [ 0 -1  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [-2 -2  0 -2 -2  0]
 [ 0  0 -2  0  0 -2]]
