**HAND JACOBIAN FOR 2R**

In [15]:
import numpy as np
def W(t, n):
    t = np.atleast_2d(t).T
    n = np.atleast_2d(n).T
    w  = np.block([t,n])
    return w

def rotation_matrix_2d(theta):
    R = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return R

def jacobian(l1,l2,theta1,theta2):
    J = np.array([[-l1*np.sin(theta1), -l2*np.sin(theta2)],
                  [l1*np.cos(theta1), l2*np.cos(theta2)]])
    return J



# test
t = np.array([0, -1])
n = np.array([1, 0])
theta = 0
theta1 = 120*(np.pi/180)
theta2 = np.pi/6
l1 = 0.866
l2 = 0.5
w= W(t, n)
R= rotation_matrix_2d(theta)
J = jacobian(l1,l2,theta1,theta2)
print(w)

print(R)

print(J)

[[ 0  1]
 [-1  0]]
[[ 1. -0.]
 [ 0.  1.]]
[[-0.749978  -0.25     ]
 [-0.433      0.4330127]]


In [16]:
def hand_jacobian(t,n,w,R,J):

    WRJ = np.dot(np.dot(w,R), J)
    O  = np.zeros((2,2))
    HJR1 = np.concatenate([WRJ,O],axis=1)
    return HJR1

HJR1 = hand_jacobian(t,n,w,R,J)
print(HJR1)


[[-0.433      0.4330127  0.         0.       ]
 [ 0.749978   0.25       0.         0.       ]]


In [17]:
t = np.array([0, 1])
n = np.array([-1, 0])
theta = 0
theta1 = 120*(np.pi/180)
theta2 = np.pi/6
l1 = 0.866
l2 = 0.5
w= W(t, n)
R= rotation_matrix_2d(theta)
J = jacobian(l1,l2,theta1,theta2)
print(w)

print(R)

print(J)

[[ 0 -1]
 [ 1  0]]
[[ 1. -0.]
 [ 0.  1.]]
[[-0.749978  -0.25     ]
 [-0.433      0.4330127]]


In [18]:
def hand_jacobian(t1,n1,w,R,J):

    WRJ = np.dot(np.dot(w,R), J)
    O  = np.zeros((2,2))
    HJR2 = np.concatenate([O,WRJ], axis = 1)
    return HJR2

HJR2 = hand_jacobian(t,n,w,R,J)
print(HJR2)

[[ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]


In [19]:
Hand_jacobian = np.concatenate([HJR1,HJR2])
print(Hand_jacobian)

[[-0.433      0.4330127  0.         0.       ]
 [ 0.749978   0.25       0.         0.       ]
 [ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]


**Hand jacobian on the corner points of ellipse.**

In [24]:
# Define ellipse
h, k = 0, 0  # Center of the ellipse
a, b = 2, 1  # Semi-major and semi-minor axis lengths

# Generate corner points of the ellipse
corner_points = [
    (h + a, k),
    (h - a, k),
    (h, k + b),
    (h, k - b)
]


In [25]:
def New_Hand_jacobian(Hand_jacobian,dx,dy):
  translation_matrix = np.array([[1,0,0,dx],
                                 [0,1,0,dy],
                                 [0,0,1,0],
                                 [0,0,0,1]])
  New_Hand_jacobian_matrix = np.dot(translation_matrix,Hand_jacobian)
  return  New_Hand_jacobian_matrix

In [29]:
for point in corner_points:
  dx,dy = point
  New_Hand_jacobian_matrix = New_Hand_jacobian(Hand_jacobian,dx,dy)
  print("Matrix at corner point ({}, {}):\n{}".format(dx, dy, New_Hand_jacobian_matrix ))
  print()

Matrix at corner point (2, 0):
[[-0.433      0.4330127 -1.499956  -0.5      ]
 [ 0.749978   0.25       0.         0.       ]
 [ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]
Matrix at corner point (-2, 0):
[[-0.433      0.4330127  1.499956   0.5      ]
 [ 0.749978   0.25       0.         0.       ]
 [ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]
Matrix at corner point (0, 1):
[[-0.433      0.4330127  0.         0.       ]
 [ 0.749978   0.25      -0.749978  -0.25     ]
 [ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]
Matrix at corner point (0, -1):
[[-0.433      0.4330127  0.         0.       ]
 [ 0.749978   0.25       0.749978   0.25     ]
 [ 0.         0.         0.433     -0.4330127]
 [ 0.         0.        -0.749978  -0.25     ]]

