In [11]:
G = np.array([[0,1,0,-1],
              [-1,0,1,0]])

In [12]:
import numpy as np

def W1(t1, n1):
    t1 = np.atleast_2d(t1).T
    n1 = np.atleast_2d(n1).T
    w1 = np.block([t1, n1])
    return w1

def rotation_matrix_2d(theta):
    R1 = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return R1

def jacobian(l1, l2, theta1, theta2):
    J1 = np.array([[-l1*np.sin(theta1), -l2*np.sin(theta2)],
                  [l1*np.cos(theta1), l2*np.cos(theta2)]])
    return J1

def hand_jacobian1(t1, n1, w1, R1, J1):
    W1R1J1 = np.dot(np.dot(w1, R1), J1)
    O1 = np.zeros((2, 2))
    HJR1 = np.concatenate([W1R1J1,O1],axis=1)
    return HJR1

def W2(t2, n2):
    t2 = np.atleast_2d(t2).T
    n2 = np.atleast_2d(n2).T
    w2 = np.block([t2, n2])
    return w2

def hand_jacobian2(t2, n2, w2, R2, J2):
    W2R2J2 = np.dot(np.dot(w2, R2), J2)
    O2 = np.zeros((2, 2))
    HJR2 = np.concatenate([O2,W2R2J2], axis=1)
    return HJR2

def manipulability_index(G, Hand_jacobian):
   GT = np.transpose(G)
   print(G)
   GI = np.linalg.inv(G@GT)
   GP = np.dot(GT,GI)
   GPT = np.transpose(GP)
   A = np.dot(GPT,Hand_jacobian)
   AT = np.transpose(A)
   mu = np.sqrt(np.linalg.det(A@AT))
   return mu
# Function to calculate manipulability index


# Define parameters
l1 = 1.5
l2 = 1
t1 = np.array([0, -1])
n1 = np.array([1, 0])
t2 = np.array([0, 1])
n2 = np.array([-1, 0])
theta = 0

# Generate 10 sets of angles
angles1 = [(2.551604917017948, -1.8234765819369751),
           (2.6061306077543263, -1.987237658382705),
           (2.614735858492477, -2.14586524634296),
           (2.5625114034177647, -2.2843286751900402),
           (2.4469645287081208, -2.382598013259652),
           (2.2935305746083126, -2.4188584057763776),
           (2.1475853640438203, -2.382598013259652),
           (2.038305319766837, -2.2843286751900402),
           (1.9675467449067312, -2.1458652463429604),
           (1.9266877915182872, -1.9872376583827052)]

angles2 = [(0.5899877365718454, 1.8234765819369754),
           (0.6743591431798454, 1.6664335535985486),
           (0.7746873625811364, 1.5268895947672183),
           (0.8793678078179165, 1.415666369606802),
           (0.978759222653162, 1.3433110968522968),
           (1.0654358165107394, 1.318116071652818),
           (1.1348639051732468, 1.3433110968522968),
           (1.1855807677582035, 1.415666369606802),
           (1.2182527987588374, 1.5268895947672183),
           (1.2340991935775376, 1.6664335535985486)]

matrices = []
for angles1_pair,angles2_pair in zip(angles1, angles2):
    theta1a, theta2a = angles1_pair
    theta1b, theta2b = angles2_pair

    # Calculate W, R, J for HJR1
    w1 = W1(t1, n1)
    R1 = rotation_matrix_2d(theta)
    J1 = jacobian(l1, l2, theta1a, theta2a)

    # Calculate W, R, J for HJR2
    w2 = W2(t2, n2)
    R2 = rotation_matrix_2d(theta)
    J2 = jacobian(l1, l2, theta1b, theta2b)

    # Calculate HJR1 and HJR2
    HJR1 = hand_jacobian1(t1, n1, w1, R1, J1)
    HJR2 = hand_jacobian2(t2, n2, w2, R2, J2)

    # Form the 4x4 matrix by concatenating HJR1 and HJR2
    Hand_jacobian = np.vstack([HJR1, HJR2])
    matrices.append(Hand_jacobian)

# Convert the list of matrices to a numpy array
matrices_array = np.array(matrices)

# Loop through each hand Jacobian matrix and calculate manipulability index
for idx, Hand_jacobian in enumerate(matrices_array):
    manip_index = manipulability_index(G, Hand_jacobian)
    print(f"Manipulability Index for Hand Jacobian Matrix {idx+1}: {manip_index}")


[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 1: 0.8124877203019847
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 2: 0.8067190281005598
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 3: 0.7956483341213308
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 4: 0.7884692115474602
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 5: 0.7794058763828958
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 6: 0.7496827365339401
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 7: 0.6932828005266608
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 8: 0.6221505652236619
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 9: 0.5515063113434185
[[ 0  1  0 -1]
 [-1  0  1  0]]
Manipulability Index for Hand Jacobian Matrix 10: 0.49737143401439265
